# Gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Environment Properties
minecraft_version=26.1.2
minecraft_version_range=[26.1.2]

neo_version=26.1.2.94
neo_version_range=[26.1.2.94,26.2)

# Mod Properties
mod_id=clipchat
mod_name=ClipChat
mod_license=CC-BY-NC-SA-4.0
mod_version=1.0.0
mod_group_id=dev.thomas7520.clipchat

# Test Dependencies
junit_version=5.11.4
